# -*- coding: utf-8 -*-
"""ArbolBinario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ty7TglAv-_kA7ZvKsFacOo5z0u1qK4CT
"""

from collections import deque

"""
Nombre: Antony Torrez Mendez
Registro: 221090045
"""

class Nodo:
    def __init__(self, valor):
        self._valor = valor
        self._izquierda = None
        self._derecha = None

    # Getters y Setters
    def get_valor(self): return self._valor
    def get_izquierda(self): return self._izquierda
    def get_derecha(self): return self._derecha
    def set_valor(self, valor): self._valor = valor
    def set_izquierda(self, nodo): self._izquierda = nodo
    def set_derecha(self, nodo): self._derecha = nodo


class ArbolBinario:
    def __init__(self):
        self._raiz = None

    # 1. InsertarNodo(x)
    def InsertarNodo(self, x):
        if self.EsVacio():
            self._raiz = Nodo(x)
        else:
            self._insertar_recursivo(self._raiz, x)

    def _insertar_recursivo(self, nodo, valor):
        if valor < nodo.get_valor():
            if nodo.get_izquierda() is None:
                nodo.set_izquierda(Nodo(valor))
            else:
                self._insertar_recursivo(nodo.get_izquierda(), valor)
        elif valor > nodo.get_valor():
            if nodo.get_derecha() is None:
                nodo.set_derecha(Nodo(valor))
            else:
                self._insertar_recursivo(nodo.get_derecha(), valor)

    # 2. EsVacio()
    def EsVacio(self):
        return self._raiz is None

    # 3. EsHoja(x)
    def EsHoja(self, x):
        nodo = self._obtener_nodo(self._raiz, x)
        if nodo:
            return nodo.get_izquierda() is None and nodo.get_derecha() is None
        return False

    def _obtener_nodo(self, nodo, valor):
        if nodo is None or nodo.get_valor() == valor:
            return nodo
        if valor < nodo.get_valor():
            return self._obtener_nodo(nodo.get_izquierda(), valor)
        return self._obtener_nodo(nodo.get_derecha(), valor)

    # 4. BuscarX(x)
    def BuscarX(self, x):
        return self._buscar_recursivo(self._raiz, x)

    def _buscar_recursivo(self, nodo, valor):
        if nodo is None: return False
        if valor == nodo.get_valor(): return True
        proximo = nodo.get_izquierda() if valor < nodo.get_valor() else nodo.get_derecha()
        return self._buscar_recursivo(proximo, valor)

    # 5. InOrden() -> (izq)(raiz)(der)
    def InOrden(self):
        lista = []
        self._in_orden_rec(self._raiz, lista)
        return "".join([f"({x})" for x in lista])

    def _in_orden_rec(self, nodo, lista):
        if nodo:
            self._in_orden_rec(nodo.get_izquierda(), lista)
            lista.append(nodo.get_valor())
            self._in_orden_rec(nodo.get_derecha(), lista)

    # 6. PostOrden() -> (izq)(der)(raiz)
    def PostOrden(self):
        lista = []
        self._post_orden_rec(self._raiz, lista)
        return "".join([f"({x})" for x in lista])

    def _post_orden_rec(self, nodo, lista):
        if nodo:
            self._post_orden_rec(nodo.get_izquierda(), lista)
            self._post_orden_rec(nodo.get_derecha(), lista)
            lista.append(nodo.get_valor())

    # 7. PreOrden() -> (raiz)(izq)(der)
    def PreOrden(self):
        lista = []
        self._pre_orden_rec(self._raiz, lista)
        return "".join([f"({x})" for x in lista])

    def _pre_orden_rec(self, nodo, lista):
        if nodo:
            lista.append(nodo.get_valor())
            self._pre_orden_rec(nodo.get_izquierda(), lista)
            self._pre_orden_rec(nodo.get_derecha(), lista)

    # --- Métodos adicionales solicitados anteriormente ---
    def Amplitud(self):
        if self.EsVacio(): return ""
        resultado = []
        cola = deque([self._raiz])
        while cola:
            n = cola.popleft()
            resultado.append(n.get_valor())
            if n.get_izquierda(): cola.append(n.get_izquierda())
            if n.get_derecha(): cola.append(n.get_derecha())
        return "".join([f"({x})" for x in resultado])

    def Cantidad(self):
        return self._contar(self._raiz)

    def _contar(self, nodo):
        if not nodo: return 0
        return 1 + self._contar(nodo.get_izquierda()) + self._contar(nodo.get_derecha())

    def Eliminar(self, x):
        self._raiz = self._eliminar_rec(self._raiz, x)

    def _eliminar_rec(self, nodo, valor):
        if not nodo: return None
        if valor < nodo.get_valor():
            nodo.set_izquierda(self._eliminar_rec(nodo.get_izquierda(), valor))
        elif valor > nodo.get_valor():
            nodo.set_derecha(self._eliminar_rec(nodo.get_derecha(), valor))
        else:
            if not nodo.get_izquierda(): return nodo.get_derecha()
            if not nodo.get_derecha(): return nodo.get_izquierda()
            temp = self._minimo(nodo.get_derecha())
            nodo.set_valor(temp.get_valor())
            nodo.set_derecha(self._eliminar_rec(nodo.get_derecha(), temp.get_valor()))
        return nodo

    def _minimo(self, nodo):
        actual = nodo
        while actual.get_izquierda(): actual = actual.get_izquierda()
        return actual

# -------------------------
# PRUEBA
# -------------------------
if __name__ == "__main__":
    arbol = ArbolBinario()

    # 1. Insertar
    for v in [50, 30, 70, 20, 40]:
        arbol.InsertarNodo(v)

    print(f"¿Está vacío?: {arbol.EsVacio()}")
    print(f"PreOrden:   {arbol.PreOrden()}")
    print(f"InOrden:    {arbol.InOrden()}")
    print(f"PostOrden:  {arbol.PostOrden()}")
    print(f"Amplitud:   {arbol.Amplitud()}")
    print(f"¿Es hoja el 20?: {arbol.EsHoja(20)}")
    print(f"¿Existe el 100?: {arbol.BuscarX(100)}")

    print(f"\n--- Eliminando el 30 ---")
    arbol.Eliminar(30)
    print(f"InOrden final: {arbol.InOrden()}")
    print(f"Cantidad restante: {arbol.Cantidad()}")